[OpnServer]
CertificatePath = "ServerCertificate.p12"
CertificatePassphrase = "1234"
Address = "127.0.0.1"
Port = 8200

[LmpServer]
Address = "127.0.0.1"
Port = 8210

[FmpServer]
Address = "127.0.0.1"
Port = 8220

[Database]
Connection = "Data Source=MHTriServer.db"
